package alerts

import (
	"fmt"
	"strings"

	"kepler-worker-go/internal/helpers"
	"kepler-worker-go/internal/models"

	"github.com/rs/zerolog/log"
)

// HandleAnomalyDetection handles anomaly detection alerts
func HandleAnomalyDetection(detection models.Detection, decision models.AlertDecision) models.AlertDecision {
	// Anomaly detections are typically high priority
	decision.ShouldAlert = true
	decision.AlertType = models.AlertTypeAnomalyDetection
	decision.Severity = models.AlertSeverityHigh
	decision.Title = CreateAnomalyTitle(detection.Label)
	decision.Description = CreateAnomalyDescription(detection)
	decision.CooldownType = "anomaly"

	// Add anomaly-specific metadata
	decision.Metadata["anomaly_label"] = detection.Label
	decision.Metadata["anomaly_confidence"] = detection.Score
	decision.Metadata["detection_method"] = "anomaly_detection"

	log.Info().
		Int32("track_id", detection.TrackID).
		Str("anomaly_type", detection.Label).
		Float32("confidence", detection.Score).
		Msg("Anomaly detection alert will be created")

	return decision
}

// BuildAnomalyAlert creates a complete anomaly alert payload with images
func BuildAnomalyAlert(detection models.Detection, cameraID string, frame []byte) models.AlertPayload {
	log.Info().
		Str("camera_id", cameraID).
		Int32("track_id", detection.TrackID).
		Str("anomaly_type", detection.Label).
		Float32("confidence", detection.Score).
		Msg("🏗️ Building anomaly alert with images")

	// Create alert decision
	decision := models.AlertDecision{
		ShouldAlert:  true,
		AlertType:    models.AlertTypeAnomalyDetection,
		Severity:     models.AlertSeverityHigh,
		Title:        CreateAnomalyTitle(detection.Label),
		Description:  CreateAnomalyDescription(detection),
		CooldownType: "anomaly",
		Metadata:     make(map[string]interface{}),
	}

	// Add anomaly-specific metadata
	decision.Metadata["anomaly_label"] = detection.Label
	decision.Metadata["anomaly_confidence"] = detection.Score
	decision.Metadata["detection_method"] = "anomaly_detection"
	decision.Metadata["requires_investigation"] = true

	// Build alert payload with images using helpers
	payload := models.AlertPayload{
		CameraID:        cameraID,
		DetectionRecord: helpers.CreateDetectionRecord(detection),
		Alert: models.Alert{
			AlertType:           decision.AlertType,
			Severity:            decision.Severity,
			Title:               decision.Title,
			Description:         decision.Description,
			DetectionConfidence: detection.Score,
			DetectionType:       detection.ClassName,
			TrackerID:           detection.TrackID,
			ProjectName:         detection.ProjectName,
			AutoGenerated:       true,
			Timestamp:           detection.Timestamp,
			AnomalyLabel:        &detection.Label,
		},
		Metadata: decision.Metadata,
	}

	// Add context image using helper
	helpers.AddContextImage(&payload, frame, cameraID, detection.TrackID, "anomaly alert")

	// Add detection image using helper with anomaly-specific metadata
	helpers.AddDetectionImage(&payload, detection, frame, cameraID, fmt.Sprintf("anomaly_alert_%d", detection.TrackID), map[string]interface{}{
		"alert_type":             decision.AlertType,
		"anomaly_label":          detection.Label,
		"detection_method":       "anomaly_detection",
		"requires_investigation": true,
	})

	return payload
}

// CreateAnomalyTitle generates appropriate title for anomaly detections
func CreateAnomalyTitle(label string) string {
	// Clean up the anomaly label for display
	cleanLabel := strings.ReplaceAll(strings.Title(label), "Anomaly", "")
	cleanLabel = strings.TrimSpace(cleanLabel)

	if cleanLabel == "" {
		return "Anomalous Behavior Detected"
	}

	return fmt.Sprintf("Anomaly Detected: %s", cleanLabel)
}

// CreateAnomalyDescription generates detailed description for anomaly detections
func CreateAnomalyDescription(detection models.Detection) string {
	description := fmt.Sprintf("Anomalous behavior detected with %.1f%% confidence", detection.Score*100)

	// Add context based on the detection label
	if strings.Contains(strings.ToLower(detection.Label), "behavior") {
		description += "\nUnusual behavioral patterns identified that deviate from normal activity."
	} else if strings.Contains(strings.ToLower(detection.Label), "object") {
		description += "\nUnexpected object or unusual object placement detected."
	} else if strings.Contains(strings.ToLower(detection.Label), "movement") {
		description += "\nAbnormal movement patterns identified."
	} else {
		description += "\nDetected activity does not match expected normal patterns."
	}

	description += "\n\n⚠️ This anomaly requires immediate investigation."

	if detection.ProjectName != "" {
		description += fmt.Sprintf("\nProject context: %s", detection.ProjectName)
	}

	return description
}
