package alerts

import (
	"fmt"
	"strings"

	"kepler-worker-go/internal/helpers"
	"kepler-worker-go/internal/models"

	"github.com/rs/zerolog/log"
)

// HandleCellphoneDetection handles cellphone detection alerts
func HandleCellphoneDetection(detection models.Detection, decision models.AlertDecision) models.AlertDecision {
	if !detection.SendAlert || detection.Score < 0.5 {
		return decision
	}

	decision.ShouldAlert = true
	decision.AlertType = models.AlertTypeCellphoneUsage
	decision.Severity = models.AlertSeverityHigh
	decision.Title = "Cellphone Usage Detected"
	decision.Description = fmt.Sprintf("Unauthorized cellphone usage detected with %.1f%% confidence", detection.Score*100)
	decision.Metadata["device_type"] = strings.ToLower(strings.ReplaceAll(detection.Label, " ", "_"))

	return decision
}

// BuildCellphoneAlert creates a complete cellphone alert payload with images
func BuildCellphoneAlert(detection models.Detection, cameraID string, frame []byte) models.AlertPayload {
	log.Info().
		Str("camera_id", cameraID).
		Int32("track_id", detection.TrackID).
		Str("device_type", detection.Label).
		Msg("🏗️ Building cellphone alert with images")

	// Create alert decision
	decision := models.AlertDecision{
		ShouldAlert:  true,
		AlertType:    models.AlertTypeCellphoneUsage,
		Severity:     models.AlertSeverityHigh,
		Title:        "Cellphone Usage Detected",
		Description:  fmt.Sprintf("Unauthorized cellphone usage detected with %.1f%% confidence", detection.Score*100),
		CooldownType: "normal",
		Metadata:     make(map[string]interface{}),
	}

	// Add cellphone-specific metadata
	decision.Metadata["device_type"] = strings.ToLower(strings.ReplaceAll(detection.Label, " ", "_"))
	decision.Metadata["detection_confidence"] = detection.Score

	// Build alert payload with images using helpers
	payload := models.AlertPayload{
		CameraID:        cameraID,
		DetectionRecord: helpers.CreateDetectionRecord(detection),
		Alert: models.Alert{
			AlertType:           decision.AlertType,
			Severity:            decision.Severity,
			Title:               decision.Title,
			Description:         decision.Description,
			DetectionConfidence: detection.Score,
			DetectionType:       detection.ClassName,
			TrackerID:           detection.TrackID,
			ProjectName:         detection.ProjectName,
			AutoGenerated:       true,
			Timestamp:           detection.Timestamp,
		},
		Metadata: decision.Metadata,
	}

	// Add context image using helper
	helpers.AddContextImage(&payload, frame, cameraID, detection.TrackID, "cellphone alert")

	// Add detection image using helper with cellphone-specific metadata
	helpers.AddDetectionImage(&payload, detection, frame, cameraID, fmt.Sprintf("cellphone_alert_%d", detection.TrackID), map[string]interface{}{
		"alert_type":  decision.AlertType,
		"device_type": strings.ToLower(strings.ReplaceAll(detection.Label, " ", "_")),
	})

	return payload
}
