package alerts

import (
	"fmt"
	"strings"

	"kepler-worker-go/internal/helpers"
	"kepler-worker-go/internal/models"

	"github.com/rs/zerolog/log"
)

// HandleGeneralDetection handles general high-confidence detections
func HandleGeneralDetection(detection models.Detection, decision models.AlertDecision) models.AlertDecision {
	if detection.Score < 0.7 && !detection.SendAlert {
		return decision
	}

	decision.ShouldAlert = true
	decision.AlertType = models.AlertTypeHighConfidence
	decision.Severity = models.AlertSeverityMedium
	decision.Title = fmt.Sprintf("%s Detection", strings.Title(detection.Label))
	decision.Description = fmt.Sprintf("%s detected with %.1f%% confidence", detection.Label, detection.Score*100)
	decision.Metadata["detection_confidence"] = detection.Score
	decision.Metadata["send_alert_flag"] = detection.SendAlert

	return decision
}

// BuildGeneralAlert creates a complete general alert payload with images
func BuildGeneralAlert(detection models.Detection, cameraID string, frame []byte) models.AlertPayload {
	log.Info().
		Str("camera_id", cameraID).
		Int32("track_id", detection.TrackID).
		Str("detection_type", detection.Label).
		Float32("confidence", detection.Score).
		Msg("🏗️ Building general alert with images")

	// Create alert decision
	decision := models.AlertDecision{
		ShouldAlert:  true,
		AlertType:    models.AlertTypeHighConfidence,
		Severity:     models.AlertSeverityMedium,
		Title:        fmt.Sprintf("%s Detection", strings.Title(detection.Label)),
		Description:  fmt.Sprintf("%s detected with %.1f%% confidence", detection.Label, detection.Score*100),
		CooldownType: "normal",
		Metadata:     make(map[string]interface{}),
	}

	// Add general-specific metadata
	decision.Metadata["detection_confidence"] = detection.Score
	decision.Metadata["send_alert_flag"] = detection.SendAlert
	decision.Metadata["detection_label"] = detection.Label

	// Build alert payload with images using helpers
	payload := models.AlertPayload{
		CameraID:        cameraID,
		DetectionRecord: helpers.CreateDetectionRecord(detection),
		Alert: models.Alert{
			AlertType:           decision.AlertType,
			Severity:            decision.Severity,
			Title:               decision.Title,
			Description:         decision.Description,
			DetectionConfidence: detection.Score,
			DetectionType:       detection.ClassName,
			TrackerID:           detection.TrackID,
			ProjectName:         detection.ProjectName,
			AutoGenerated:       true,
			Timestamp:           detection.Timestamp,
		},
		Metadata: decision.Metadata,
	}

	// Add context image using helper
	helpers.AddContextImage(&payload, frame, cameraID, detection.TrackID, "general alert")

	// Add detection image using helper with general-specific metadata
	helpers.AddDetectionImage(&payload, detection, frame, cameraID, fmt.Sprintf("general_alert_%d", detection.TrackID), map[string]interface{}{
		"alert_type":      decision.AlertType,
		"detection_label": detection.Label,
		"send_alert_flag": detection.SendAlert,
	})

	return payload
}
