package alerts

import (
	"fmt"
	"strings"

	"kepler-worker-go/internal/helpers"
	"kepler-worker-go/internal/models"

	"github.com/rs/zerolog/log"
)

// HandleGeneralDetection handles general high-confidence detections
func HandleGeneralDetection(detection models.Detection, decision models.AlertDecision) models.AlertDecision {
	if detection.Score < 0.7 && !detection.SendAlert {
		return decision
	}

	decision.ShouldAlert = true
	decision.AlertType = models.AlertTypeGeneralDetection
	decision.Severity = models.AlertSeverityMedium
	decision.Title = fmt.Sprintf("%s Detection", strings.Title(detection.Label))
	decision.Description = fmt.Sprintf("%s detected with %.1f%% confidence", detection.Label, detection.Score*100)
	decision.Metadata["detection_confidence"] = detection.Score
	decision.Metadata["send_alert_flag"] = detection.SendAlert

	return decision
}

// BuildGeneralAlert creates a complete general alert payload with images
func BuildGeneralAlert(detection models.Detection, cameraID string, frame []byte) models.AlertPayload {

	// Create alert decision
	decision := models.AlertDecision{
		ShouldAlert:  true,
		AlertType:    models.AlertTypeGeneralDetection,
		Severity:     models.AlertSeverityMedium,
		Title:        fmt.Sprintf("%s Detection", strings.Title(detection.Label)),
		Description:  fmt.Sprintf("%s detected with %.1f%% confidence", detection.Label, detection.Score*100),
		CooldownType: "normal",
		Metadata:     make(map[string]interface{}),
	}

	// Add general-specific metadata
	decision.Metadata["detection_confidence"] = detection.Score
	decision.Metadata["send_alert_flag"] = detection.SendAlert
	decision.Metadata["detection_label"] = detection.Label

	// Build alert payload with images using helpers
	payload := models.AlertPayload{
		CameraID:        cameraID,
		DetectionRecord: helpers.CreateDetectionRecord(detection),
		Alert: models.Alert{
			AlertType:           decision.AlertType,
			Severity:            decision.Severity,
			Title:               decision.Title,
			Description:         decision.Description,
			DetectionConfidence: detection.Score,
			DetectionType:       detection.ClassName,
			TrackerID:           detection.TrackID,
			ProjectName:         detection.ProjectName,
			ModelName:           detection.ModelName,
			AutoGenerated:       true,
			Timestamp:           detection.Timestamp,
		},
		Metadata: decision.Metadata,
	}

	// Add context image using helper
	helpers.AddContextImage(&payload, frame, cameraID, detection.TrackID, "general alert")

	// Add detection image using helper with general-specific metadata (using raw frame)
	helpers.AddDetectionImage(&payload, detection, frame, cameraID, fmt.Sprintf("general_alert_%d", detection.TrackID), map[string]interface{}{
		"alert_type":      decision.AlertType,
		"detection_label": detection.Label,
		"send_alert_flag": detection.SendAlert,
	})

	return payload
}

// BuildConsolidatedGeneralAlert creates a consolidated general alert for multiple detections
func BuildConsolidatedGeneralAlert(detections []models.Detection, cameraID string, rawFrame []byte, annotatedFrame []byte) models.AlertPayload {
	if len(detections) == 0 {
		log.Warn().Str("camera_id", cameraID).Msg("No detections provided for consolidated general alert")
		return models.AlertPayload{}
	}

	// Get the primary detection (highest confidence) for main alert info
	primaryDetection := findHighestConfidenceDetection(detections)
	totalDetections := len(detections)

	// Create alert decision
	decision := models.AlertDecision{
		ShouldAlert:  true,
		AlertType:    models.AlertTypeGeneralDetection,
		Severity:     models.AlertSeverityMedium,
		Title:        fmt.Sprintf("%s Detection (%d objects)", strings.Title(primaryDetection.Label), totalDetections),
		Description:  fmt.Sprintf("%d %s objects detected with high confidence", totalDetections, primaryDetection.Label),
		CooldownType: "normal",
		Metadata:     make(map[string]interface{}),
	}

	// Add general-specific metadata
	decision.Metadata["detection_confidence"] = primaryDetection.Score
	decision.Metadata["send_alert_flag"] = primaryDetection.SendAlert
	decision.Metadata["detection_label"] = primaryDetection.Label
	decision.Metadata["total_detections"] = totalDetections

	// Build alert payload using primary detection for core info
	payload := models.AlertPayload{
		CameraID:        cameraID,
		DetectionRecord: helpers.CreateDetectionRecord(primaryDetection),
		Alert: models.Alert{
			AlertType:           decision.AlertType,
			Severity:            decision.Severity,
			Title:               decision.Title,
			Description:         decision.Description,
			DetectionConfidence: primaryDetection.Score,
			DetectionType:       primaryDetection.ClassName,
			TrackerID:           primaryDetection.TrackID,
			ProjectName:         primaryDetection.ProjectName,
			ModelName:           primaryDetection.ModelName,
			AutoGenerated:       true,
			Timestamp:           primaryDetection.Timestamp,
		},
		Metadata: decision.Metadata,
	}

	// Add context image using annotated frame (shows full scene with overlays)
	helpers.AddContextImage(&payload, annotatedFrame, cameraID, primaryDetection.TrackID, "Consolidated general alert")

	// Add detection images: primary from annotated (with overlays), others from raw (clean)
	for i, detection := range detections {
		frameForCrop := rawFrame
		if detection.TrackID == primaryDetection.TrackID {
			frameForCrop = annotatedFrame
		}
		helpers.AddDetectionImage(&payload, detection, frameForCrop, cameraID,
			fmt.Sprintf("general_consolidated_%d_%d", detection.TrackID, i),
			map[string]interface{}{
				"alert_type":       decision.AlertType,
				"detection_label":  detection.Label,
				"send_alert_flag":  detection.SendAlert,
				"detection_index":  i,
				"total_detections": totalDetections,
			})
	}

	return payload
}

// Helper function to find highest confidence detection
func findHighestConfidenceDetection(detections []models.Detection) models.Detection {
	if len(detections) == 1 {
		return detections[0]
	}

	highest := detections[0]
	for _, det := range detections[1:] {
		if det.Score > highest.Score {
			highest = det
		}
	}
	return highest
}
