package alerts

import (
	"fmt"

	"kepler-worker-go/internal/helpers"
	"kepler-worker-go/internal/models"

	"github.com/rs/zerolog/log"
)

// HandleIntrusionDetection determines if an intrusion alert should be created
func HandleIntrusionDetection(detection models.Detection, decision models.AlertDecision) models.AlertDecision {
	if detection.IsIntrusion == nil || !*detection.IsIntrusion {
		return decision
	}

	decision.ShouldAlert = true
	decision.AlertType = models.AlertTypeIntrusion
	decision.Severity = models.AlertSeverityHigh
	decision.Title = "Intrusion Detected"
	decision.Description = fmt.Sprintf("Intrusion detected with %.1f%% confidence", detection.Score*100)
	decision.Metadata["is_intrusion"] = true

	log.Info().
		Int32("track_id", detection.TrackID).
		Float32("confidence", detection.Score).
		Msg("Intrusion alert will be created")

	return decision
}

// BuildIntrusionAlert creates a complete intrusion alert payload with images
func BuildIntrusionAlert(detection models.Detection, cameraID string, frame []byte) models.AlertPayload {
	log.Info().
		Str("camera_id", cameraID).
		Int32("track_id", detection.TrackID).
		Msg("🏗️ Building intrusion alert with images")

	decision := models.AlertDecision{
		ShouldAlert:  true,
		AlertType:    models.AlertTypeIntrusion,
		Severity:     models.AlertSeverityHigh,
		Title:        "Intrusion Detected",
		Description:  fmt.Sprintf("Intrusion detected with %.1f%% confidence", detection.Score*100),
		CooldownType: "normal",
		Metadata:     map[string]interface{}{"is_intrusion": true},
	}

	payload := models.AlertPayload{
		CameraID:        cameraID,
		DetectionRecord: helpers.CreateDetectionRecord(detection),
		Alert: models.Alert{
			AlertType:           decision.AlertType,
			Severity:            decision.Severity,
			Title:               decision.Title,
			Description:         decision.Description,
			DetectionConfidence: detection.Score,
			DetectionType:       detection.ClassName,
			TrackerID:           detection.TrackID,
			ProjectName:         detection.ProjectName,
			AutoGenerated:       true,
			Timestamp:           detection.Timestamp,
		},
		Metadata: decision.Metadata,
	}

	// Context + detection crop from annotated frame by default
	helpers.AddContextImage(&payload, frame, cameraID, detection.TrackID, "intrusion alert")
	helpers.AddDetectionImage(&payload, detection, frame, cameraID, fmt.Sprintf("intrusion_alert_%d", detection.TrackID), map[string]interface{}{
		"alert_type":   decision.AlertType,
		"is_intrusion": true,
	})

	return payload
}
