package alerts

import (
	"fmt"
	"strings"

	"kepler-worker-go/internal/helpers"
	"kepler-worker-go/internal/models"

	"github.com/rs/zerolog/log"
)

// HandlePPEDetection handles PPE detection alerts
func HandlePPEDetection(detection models.Detection, decision models.AlertDecision) models.AlertDecision {
	// PPE alerts are only created for persons with violations and send_alert=true
	if !detection.SendAlert {
		log.Debug().
			Int32("track_id", detection.TrackID).
			Msg("PPE detection: send_alert=false, no alert created")
		return decision
	}

	if strings.ToLower(detection.ClassName) != "person" {
		log.Debug().
			Str("class_name", detection.ClassName).
			Msg("PPE detection: not a person, no alert created")
		return decision
	}

	if len(detection.Violations) == 0 {
		log.Debug().
			Int32("track_id", detection.TrackID).
			Msg("PPE detection: no violations, no alert created")
		return decision
	}

	decision.ShouldAlert = true
	decision.AlertType = models.AlertTypePPEViolation
	decision.Severity = models.AlertSeverityHigh
	decision.Title = CreatePPETitle(detection.Violations)
	decision.Description = CreatePPEDescription(detection)
	decision.Metadata["ppe_violations"] = detection.Violations
	decision.Metadata["ppe_compliance"] = detection.Compliance
	decision.Metadata["violation_count"] = len(detection.Violations)

	log.Info().
		Int32("track_id", detection.TrackID).
		Int("violation_count", len(detection.Violations)).
		Strs("violations", detection.Violations).
		Msg("PPE violation alert will be created")

	return decision
}

// BuildPPEAlert creates a complete PPE alert payload with images
func BuildPPEAlert(detection models.Detection, cameraID string, frame []byte) models.AlertPayload {
	log.Info().
		Str("camera_id", cameraID).
		Int32("track_id", detection.TrackID).
		Int("violation_count", len(detection.Violations)).
		Msg("🏗️ Building PPE alert with images")

	// Create alert decision first
	decision := models.AlertDecision{
		ShouldAlert:  true,
		AlertType:    models.AlertTypePPEViolation,
		Severity:     models.AlertSeverityHigh,
		Title:        CreatePPETitle(detection.Violations),
		Description:  CreatePPEDescription(detection),
		CooldownType: "normal",
		Metadata:     make(map[string]interface{}),
	}

	// Add PPE-specific metadata
	decision.Metadata["ppe_violations"] = detection.Violations
	decision.Metadata["ppe_compliance"] = detection.Compliance
	decision.Metadata["violation_count"] = len(detection.Violations)

	// Build alert payload with images using helpers
	payload := models.AlertPayload{
		CameraID:        cameraID,
		DetectionRecord: helpers.CreateDetectionRecord(detection),
		Alert: models.Alert{
			AlertType:           decision.AlertType,
			Severity:            decision.Severity,
			Title:               decision.Title,
			Description:         decision.Description,
			DetectionConfidence: detection.Score,
			DetectionType:       detection.ClassName,
			TrackerID:           detection.TrackID,
			ProjectName:         detection.ProjectName,
			AutoGenerated:       true,
			Timestamp:           detection.Timestamp,
			PPEViolations:       detection.Violations,
			PPECompliance:       detection.Compliance,
			ViolationCount:      len(detection.Violations),
			ViolationTypes:      detection.Violations,
		},
		Metadata: decision.Metadata,
	}

	// Add context image using helper
	helpers.AddContextImage(&payload, frame, cameraID, detection.TrackID, "PPE alert")

	// Add detection image using helper with PPE-specific metadata
	helpers.AddDetectionImage(&payload, detection, frame, cameraID, fmt.Sprintf("ppe_alert_%d", detection.TrackID), map[string]interface{}{
		"alert_type": decision.AlertType,
		"violations": detection.Violations,
	})

	return payload
}

// CreatePPETitle generates appropriate title for PPE violations
func CreatePPETitle(violations []string) string {
	if len(violations) == 1 {
		return fmt.Sprintf("PPE Violation: %s", strings.Title(strings.ReplaceAll(violations[0], " violation", "")))
	}
	return fmt.Sprintf("Multiple PPE Violations (%d items)", len(violations))
}

// CreatePPEDescription generates detailed description for PPE violations
func CreatePPEDescription(detection models.Detection) string {
	violationDetails := make([]string, 0, len(detection.Violations))
	for _, violation := range detection.Violations {
		switch {
		case strings.Contains(strings.ToLower(violation), "vest"):
			violationDetails = append(violationDetails, "❌ Missing Safety Vest")
		case strings.Contains(strings.ToLower(violation), "helmet"):
			violationDetails = append(violationDetails, "❌ Missing Safety Helmet")
		case strings.Contains(strings.ToLower(violation), "glasses"):
			violationDetails = append(violationDetails, "❌ Missing Safety Glasses")
		case strings.Contains(strings.ToLower(violation), "gloves"):
			violationDetails = append(violationDetails, "❌ Missing Safety Gloves")
		default:
			violationDetails = append(violationDetails, fmt.Sprintf("❌ %s", strings.Title(violation)))
		}
	}

	description := fmt.Sprintf("PPE safety violations detected:\n%s", strings.Join(violationDetails, "\n"))
	description += fmt.Sprintf("\n\nDetection confidence: %.1f%%", detection.Score*100)

	if detection.Compliance != nil {
		description += fmt.Sprintf("\nCompliance status: %s", strings.Title(*detection.Compliance))
	}

	return description
}
