// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/detection.proto

package detection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetectionService_InferDetection_FullMethodName       = "/detection.DetectionService/InferDetection"
	DetectionService_SaveFalseDetection_FullMethodName   = "/detection.DetectionService/SaveFalseDetection"
	DetectionService_RemoveFalseDetection_FullMethodName = "/detection.DetectionService/RemoveFalseDetection"
	DetectionService_HealthCheck_FullMethodName          = "/detection.DetectionService/HealthCheck"
	DetectionService_GetActivePipelines_FullMethodName   = "/detection.DetectionService/GetActivePipelines"
	DetectionService_RemovePipelines_FullMethodName      = "/detection.DetectionService/RemovePipelines"
	DetectionService_SetROI_FullMethodName               = "/detection.DetectionService/SetROI"
	DetectionService_InitializeROI_FullMethodName        = "/detection.DetectionService/InitializeROI"
	DetectionService_AddFace_FullMethodName              = "/detection.DetectionService/AddFace"
)

// DetectionServiceClient is the client API for DetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectionServiceClient interface {
	// Process frame for object detection across multiple projects
	InferDetection(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*DetectionResponse, error)
	// Save false detection data
	SaveFalseDetection(ctx context.Context, in *ROIRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Remove false detection data
	RemoveFalseDetection(ctx context.Context, in *RemoveROIRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Health check endpoint
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// Get active pipelines
	GetActivePipelines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PipelinesResponse, error)
	// Remove pipelines for a camera
	RemovePipelines(ctx context.Context, in *CameraIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Set ROI for a solution
	SetROI(ctx context.Context, in *SolutionROIRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Initialize ROI for camera startup or ROI updates (send once, not every frame)
	InitializeROI(ctx context.Context, in *ROIRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Add a face to the face embeddings database (for face_detection_sr project)
	AddFace(ctx context.Context, in *AddFaceRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type detectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectionServiceClient(cc grpc.ClientConnInterface) DetectionServiceClient {
	return &detectionServiceClient{cc}
}

func (c *detectionServiceClient) InferDetection(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*DetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionResponse)
	err := c.cc.Invoke(ctx, DetectionService_InferDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) SaveFalseDetection(ctx context.Context, in *ROIRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DetectionService_SaveFalseDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) RemoveFalseDetection(ctx context.Context, in *RemoveROIRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DetectionService_RemoveFalseDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DetectionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) GetActivePipelines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PipelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipelinesResponse)
	err := c.cc.Invoke(ctx, DetectionService_GetActivePipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) RemovePipelines(ctx context.Context, in *CameraIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DetectionService_RemovePipelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) SetROI(ctx context.Context, in *SolutionROIRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DetectionService_SetROI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) InitializeROI(ctx context.Context, in *ROIRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DetectionService_InitializeROI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectionServiceClient) AddFace(ctx context.Context, in *AddFaceRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DetectionService_AddFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectionServiceServer is the server API for DetectionService service.
// All implementations must embed UnimplementedDetectionServiceServer
// for forward compatibility.
type DetectionServiceServer interface {
	// Process frame for object detection across multiple projects
	InferDetection(context.Context, *FrameRequest) (*DetectionResponse, error)
	// Save false detection data
	SaveFalseDetection(context.Context, *ROIRequest) (*StatusResponse, error)
	// Remove false detection data
	RemoveFalseDetection(context.Context, *RemoveROIRequest) (*StatusResponse, error)
	// Health check endpoint
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	// Get active pipelines
	GetActivePipelines(context.Context, *Empty) (*PipelinesResponse, error)
	// Remove pipelines for a camera
	RemovePipelines(context.Context, *CameraIdRequest) (*StatusResponse, error)
	// Set ROI for a solution
	SetROI(context.Context, *SolutionROIRequest) (*StatusResponse, error)
	// Initialize ROI for camera startup or ROI updates (send once, not every frame)
	InitializeROI(context.Context, *ROIRequest) (*StatusResponse, error)
	// Add a face to the face embeddings database (for face_detection_sr project)
	AddFace(context.Context, *AddFaceRequest) (*StatusResponse, error)
	mustEmbedUnimplementedDetectionServiceServer()
}

// UnimplementedDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectionServiceServer struct{}

func (UnimplementedDetectionServiceServer) InferDetection(context.Context, *FrameRequest) (*DetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InferDetection not implemented")
}
func (UnimplementedDetectionServiceServer) SaveFalseDetection(context.Context, *ROIRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFalseDetection not implemented")
}
func (UnimplementedDetectionServiceServer) RemoveFalseDetection(context.Context, *RemoveROIRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFalseDetection not implemented")
}
func (UnimplementedDetectionServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDetectionServiceServer) GetActivePipelines(context.Context, *Empty) (*PipelinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivePipelines not implemented")
}
func (UnimplementedDetectionServiceServer) RemovePipelines(context.Context, *CameraIdRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePipelines not implemented")
}
func (UnimplementedDetectionServiceServer) SetROI(context.Context, *SolutionROIRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetROI not implemented")
}
func (UnimplementedDetectionServiceServer) InitializeROI(context.Context, *ROIRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeROI not implemented")
}
func (UnimplementedDetectionServiceServer) AddFace(context.Context, *AddFaceRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFace not implemented")
}
func (UnimplementedDetectionServiceServer) mustEmbedUnimplementedDetectionServiceServer() {}
func (UnimplementedDetectionServiceServer) testEmbeddedByValue()                          {}

// UnsafeDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectionServiceServer will
// result in compilation errors.
type UnsafeDetectionServiceServer interface {
	mustEmbedUnimplementedDetectionServiceServer()
}

func RegisterDetectionServiceServer(s grpc.ServiceRegistrar, srv DetectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectionService_ServiceDesc, srv)
}

func _DetectionService_InferDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).InferDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_InferDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).InferDetection(ctx, req.(*FrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_SaveFalseDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ROIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).SaveFalseDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_SaveFalseDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).SaveFalseDetection(ctx, req.(*ROIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_RemoveFalseDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveROIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).RemoveFalseDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_RemoveFalseDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).RemoveFalseDetection(ctx, req.(*RemoveROIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_GetActivePipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).GetActivePipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_GetActivePipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).GetActivePipelines(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_RemovePipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CameraIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).RemovePipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_RemovePipelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).RemovePipelines(ctx, req.(*CameraIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_SetROI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolutionROIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).SetROI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_SetROI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).SetROI(ctx, req.(*SolutionROIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_InitializeROI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ROIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).InitializeROI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_InitializeROI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).InitializeROI(ctx, req.(*ROIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DetectionService_AddFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectionServiceServer).AddFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectionService_AddFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectionServiceServer).AddFace(ctx, req.(*AddFaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectionService_ServiceDesc is the grpc.ServiceDesc for DetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detection.DetectionService",
	HandlerType: (*DetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InferDetection",
			Handler:    _DetectionService_InferDetection_Handler,
		},
		{
			MethodName: "SaveFalseDetection",
			Handler:    _DetectionService_SaveFalseDetection_Handler,
		},
		{
			MethodName: "RemoveFalseDetection",
			Handler:    _DetectionService_RemoveFalseDetection_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DetectionService_HealthCheck_Handler,
		},
		{
			MethodName: "GetActivePipelines",
			Handler:    _DetectionService_GetActivePipelines_Handler,
		},
		{
			MethodName: "RemovePipelines",
			Handler:    _DetectionService_RemovePipelines_Handler,
		},
		{
			MethodName: "SetROI",
			Handler:    _DetectionService_SetROI_Handler,
		},
		{
			MethodName: "InitializeROI",
			Handler:    _DetectionService_InitializeROI_Handler,
		},
		{
			MethodName: "AddFace",
			Handler:    _DetectionService_AddFace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/detection.proto",
}
