// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/detection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for requests that don't need parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{0}
}

// Request message containing camera ID
type CameraIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraIdRequest) Reset() {
	*x = CameraIdRequest{}
	mi := &file_proto_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraIdRequest) ProtoMessage() {}

func (x *CameraIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraIdRequest.ProtoReflect.Descriptor instead.
func (*CameraIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{1}
}

func (x *CameraIdRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

// Request message for frame processing
type FrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // Encoded image bytes (e.g., JPEG/PNG)
	CameraId      string                 `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	ProjectNames  []string               `protobuf:"bytes,3,rep,name=project_names,json=projectNames,proto3" json:"project_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_proto_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{2}
}

func (x *FrameRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *FrameRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *FrameRequest) GetProjectNames() []string {
	if x != nil {
		return x.ProjectNames
	}
	return nil
}

// Request message for saving false detections
type ROIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // Base64 encoded image
	CameraId      string                 `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	RoiId         string                 `protobuf:"bytes,3,opt,name=roi_id,json=roiId,proto3" json:"roi_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ModelName     string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ROIRequest) Reset() {
	*x = ROIRequest{}
	mi := &file_proto_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ROIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROIRequest) ProtoMessage() {}

func (x *ROIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROIRequest.ProtoReflect.Descriptor instead.
func (*ROIRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{3}
}

func (x *ROIRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ROIRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *ROIRequest) GetRoiId() string {
	if x != nil {
		return x.RoiId
	}
	return ""
}

func (x *ROIRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ROIRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

// Request message for remove false detections
type RemoveROIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	RoiId         string                 `protobuf:"bytes,2,opt,name=roi_id,json=roiId,proto3" json:"roi_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ModelName     string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveROIRequest) Reset() {
	*x = RemoveROIRequest{}
	mi := &file_proto_detection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveROIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveROIRequest) ProtoMessage() {}

func (x *RemoveROIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveROIRequest.ProtoReflect.Descriptor instead.
func (*RemoveROIRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveROIRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *RemoveROIRequest) GetRoiId() string {
	if x != nil {
		return x.RoiId
	}
	return ""
}

func (x *RemoveROIRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *RemoveROIRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

// Request message for saving true detections to True Bucket
type TrueDetectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"` // Base64 encoded image
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ObjectType    string                 `protobuf:"bytes,4,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"` // e.g., "Car", "Truck", "Person", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrueDetectionRequest) Reset() {
	*x = TrueDetectionRequest{}
	mi := &file_proto_detection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrueDetectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrueDetectionRequest) ProtoMessage() {}

func (x *TrueDetectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrueDetectionRequest.ProtoReflect.Descriptor instead.
func (*TrueDetectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{5}
}

func (x *TrueDetectionRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *TrueDetectionRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TrueDetectionRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *TrueDetectionRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

// Request message for removing true detections from True Bucket
type RemoveTrueDetectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ObjectType    string                 `protobuf:"bytes,3,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`          // e.g., "Car", "Truck", "Person", etc.
	DetectionId   *string                `protobuf:"bytes,4,opt,name=detection_id,json=detectionId,proto3,oneof" json:"detection_id,omitempty"` // Optional: if provided, removes specific detection; if not provided, removes all for object_type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrueDetectionRequest) Reset() {
	*x = RemoveTrueDetectionRequest{}
	mi := &file_proto_detection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrueDetectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrueDetectionRequest) ProtoMessage() {}

func (x *RemoveTrueDetectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrueDetectionRequest.ProtoReflect.Descriptor instead.
func (*RemoveTrueDetectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveTrueDetectionRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *RemoveTrueDetectionRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *RemoveTrueDetectionRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *RemoveTrueDetectionRequest) GetDetectionId() string {
	if x != nil && x.DetectionId != nil {
		return *x.DetectionId
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // This represents List[int]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_detection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{7}
}

func (x *Point) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Request message to set ROI
type SolutionROIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	SolutionName  string                 `protobuf:"bytes,3,opt,name=solution_name,json=solutionName,proto3" json:"solution_name,omitempty"`
	RoiPts        []*Point               `protobuf:"bytes,4,rep,name=roi_pts,json=roiPts,proto3" json:"roi_pts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolutionROIRequest) Reset() {
	*x = SolutionROIRequest{}
	mi := &file_proto_detection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolutionROIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolutionROIRequest) ProtoMessage() {}

func (x *SolutionROIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolutionROIRequest.ProtoReflect.Descriptor instead.
func (*SolutionROIRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{8}
}

func (x *SolutionROIRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *SolutionROIRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *SolutionROIRequest) GetSolutionName() string {
	if x != nil {
		return x.SolutionName
	}
	return ""
}

func (x *SolutionROIRequest) GetRoiPts() []*Point {
	if x != nil {
		return x.RoiPts
	}
	return nil
}

// Response message for detection results
type DetectionResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Results       map[string]*ProjectDetections `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResponse) Reset() {
	*x = DetectionResponse{}
	mi := &file_proto_detection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResponse) ProtoMessage() {}

func (x *DetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResponse.ProtoReflect.Descriptor instead.
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{9}
}

func (x *DetectionResponse) GetResults() map[string]*ProjectDetections {
	if x != nil {
		return x.Results
	}
	return nil
}

// Container for detection results per project
type ProjectDetections struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	PrimaryDetections   []*Detection               `protobuf:"bytes,1,rep,name=primary_detections,json=primaryDetections,proto3" json:"primary_detections,omitempty"`
	SecondaryDetections []*Detection               `protobuf:"bytes,2,rep,name=secondary_detections,json=secondaryDetections,proto3" json:"secondary_detections,omitempty"`
	TertiaryDetections  []*Detection               `protobuf:"bytes,3,rep,name=tertiary_detections,json=tertiaryDetections,proto3" json:"tertiary_detections,omitempty"`
	Solutions           map[string]*SolutionResult `protobuf:"bytes,4,rep,name=solutions,proto3" json:"solutions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProjectDetections) Reset() {
	*x = ProjectDetections{}
	mi := &file_proto_detection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectDetections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDetections) ProtoMessage() {}

func (x *ProjectDetections) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDetections.ProtoReflect.Descriptor instead.
func (*ProjectDetections) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectDetections) GetPrimaryDetections() []*Detection {
	if x != nil {
		return x.PrimaryDetections
	}
	return nil
}

func (x *ProjectDetections) GetSecondaryDetections() []*Detection {
	if x != nil {
		return x.SecondaryDetections
	}
	return nil
}

func (x *ProjectDetections) GetTertiaryDetections() []*Detection {
	if x != nil {
		return x.TertiaryDetections
	}
	return nil
}

func (x *ProjectDetections) GetSolutions() map[string]*SolutionResult {
	if x != nil {
		return x.Solutions
	}
	return nil
}

// Single detection result
type Detection struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Bbox         []float32              `protobuf:"fixed32,1,rep,packed,name=bbox,proto3" json:"bbox,omitempty"` // [x1, y1, x2, y2]
	Confidence   float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ClassId      int32                  `protobuf:"varint,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName    string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	TrackId      int32                  `protobuf:"varint,5,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	ParentId     int32                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	FalseMatchId string                 `protobuf:"bytes,7,opt,name=false_match_id,json=falseMatchId,proto3" json:"false_match_id,omitempty"`
	SendAlert    bool                   `protobuf:"varint,8,opt,name=send_alert,json=sendAlert,proto3" json:"send_alert,omitempty"`
	FrameNum     int32                  `protobuf:"varint,9,opt,name=frame_num,json=frameNum,proto3" json:"frame_num,omitempty"`
	IsRpn        bool                   `protobuf:"varint,27,opt,name=is_rpn,json=isRpn,proto3" json:"is_rpn,omitempty"`
	TrueMatchId  *string                `protobuf:"bytes,28,opt,name=true_match_id,json=trueMatchId,proto3,oneof" json:"true_match_id,omitempty"`
	// PPE Alerts (optional fields)
	HasVest    *bool    `protobuf:"varint,10,opt,name=has_vest,json=hasVest,proto3,oneof" json:"has_vest,omitempty"`
	HasHelmet  *bool    `protobuf:"varint,11,opt,name=has_helmet,json=hasHelmet,proto3,oneof" json:"has_helmet,omitempty"`
	HasHead    *bool    `protobuf:"varint,26,opt,name=has_head,json=hasHead,proto3,oneof" json:"has_head,omitempty"`
	Compliance *string  `protobuf:"bytes,12,opt,name=compliance,proto3,oneof" json:"compliance,omitempty"`
	HasGloves  *bool    `protobuf:"varint,13,opt,name=has_gloves,json=hasGloves,proto3,oneof" json:"has_gloves,omitempty"`
	HasGlasses *bool    `protobuf:"varint,14,opt,name=has_glasses,json=hasGlasses,proto3,oneof" json:"has_glasses,omitempty"`
	Violations []string `protobuf:"bytes,15,rep,name=violations,proto3" json:"violations,omitempty"`
	PpeItems   []string `protobuf:"bytes,16,rep,name=ppe_items,json=ppeItems,proto3" json:"ppe_items,omitempty"`
	// Bike Helmet Detection (separate from PPE)
	HasBikeHelmet *bool `protobuf:"varint,29,opt,name=has_bike_helmet,json=hasBikeHelmet,proto3,oneof" json:"has_bike_helmet,omitempty"`
	// Tripling Alert (for two-wheelers with more than 2 people)
	Tripling *bool `protobuf:"varint,30,opt,name=tripling,proto3,oneof" json:"tripling,omitempty"`
	// Merged bounding box for person+two-wheeler when helmet not detected (fovea helmet detection)
	MergedBbox []float32 `protobuf:"fixed32,31,rep,packed,name=merged_bbox,json=mergedBbox,proto3" json:"merged_bbox,omitempty"` // [x1, y1, x2, y2] - merged box covering person and two-wheeler
	// Tripling merged bounding box for multiple people on two-wheeler (fovea tripling detection)
	TriplingMergedBbox []float32 `protobuf:"fixed32,32,rep,packed,name=tripling_merged_bbox,json=triplingMergedBbox,proto3" json:"tripling_merged_bbox,omitempty"` // [x1, y1, x2, y2] - merged box for tripling violations
	// Intrusion Alerts
	IsIntrusion *bool `protobuf:"varint,17,opt,name=is_intrusion,json=isIntrusion,proto3,oneof" json:"is_intrusion,omitempty"`
	// Numberplate Recognition
	Plate     *string   `protobuf:"bytes,18,opt,name=plate,proto3,oneof" json:"plate,omitempty"`
	PlateBbox []float32 `protobuf:"fixed32,36,rep,packed,name=plate_bbox,json=plateBbox,proto3" json:"plate_bbox,omitempty"`
	// Cloth Color Detection
	Color *string `protobuf:"bytes,19,opt,name=color,proto3,oneof" json:"color,omitempty"`
	// Gender Classification
	Gender *string `protobuf:"bytes,20,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	// Loitering Detection
	IsLoitering  *bool    `protobuf:"varint,21,opt,name=is_loitering,json=isLoitering,proto3,oneof" json:"is_loitering,omitempty"`
	TimeInRegion *float32 `protobuf:"fixed32,22,opt,name=time_in_region,json=timeInRegion,proto3,oneof" json:"time_in_region,omitempty"`
	// vessel Classification
	VesselType *string `protobuf:"bytes,23,opt,name=vessel_type,json=vesselType,proto3,oneof" json:"vessel_type,omitempty"`
	// face Recognition
	RecognitionId    *string  `protobuf:"bytes,24,opt,name=recognition_id,json=recognitionId,proto3,oneof" json:"recognition_id,omitempty"`
	RecognitionScore *float32 `protobuf:"fixed32,25,opt,name=recognition_score,json=recognitionScore,proto3,oneof" json:"recognition_score,omitempty"`
	// Red Light Violation
	RedlightViolation *bool `protobuf:"varint,33,opt,name=redlight_violation,json=redlightViolation,proto3,oneof" json:"redlight_violation,omitempty"`
	// Vehicle Speed Detection
	SpeedKmph *float32 `protobuf:"fixed32,34,opt,name=speed_kmph,json=speedKmph,proto3,oneof" json:"speed_kmph,omitempty"` // Speed in km/h for vehicles
	// Wrong Lane Detection
	WrongLane     *bool `protobuf:"varint,35,opt,name=wrong_lane,json=wrongLane,proto3,oneof" json:"wrong_lane,omitempty"` // True if vehicle is in wrong lane
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_proto_detection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{11}
}

func (x *Detection) GetBbox() []float32 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Detection) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Detection) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *Detection) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Detection) GetFalseMatchId() string {
	if x != nil {
		return x.FalseMatchId
	}
	return ""
}

func (x *Detection) GetSendAlert() bool {
	if x != nil {
		return x.SendAlert
	}
	return false
}

func (x *Detection) GetFrameNum() int32 {
	if x != nil {
		return x.FrameNum
	}
	return 0
}

func (x *Detection) GetIsRpn() bool {
	if x != nil {
		return x.IsRpn
	}
	return false
}

func (x *Detection) GetTrueMatchId() string {
	if x != nil && x.TrueMatchId != nil {
		return *x.TrueMatchId
	}
	return ""
}

func (x *Detection) GetHasVest() bool {
	if x != nil && x.HasVest != nil {
		return *x.HasVest
	}
	return false
}

func (x *Detection) GetHasHelmet() bool {
	if x != nil && x.HasHelmet != nil {
		return *x.HasHelmet
	}
	return false
}

func (x *Detection) GetHasHead() bool {
	if x != nil && x.HasHead != nil {
		return *x.HasHead
	}
	return false
}

func (x *Detection) GetCompliance() string {
	if x != nil && x.Compliance != nil {
		return *x.Compliance
	}
	return ""
}

func (x *Detection) GetHasGloves() bool {
	if x != nil && x.HasGloves != nil {
		return *x.HasGloves
	}
	return false
}

func (x *Detection) GetHasGlasses() bool {
	if x != nil && x.HasGlasses != nil {
		return *x.HasGlasses
	}
	return false
}

func (x *Detection) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *Detection) GetPpeItems() []string {
	if x != nil {
		return x.PpeItems
	}
	return nil
}

func (x *Detection) GetHasBikeHelmet() bool {
	if x != nil && x.HasBikeHelmet != nil {
		return *x.HasBikeHelmet
	}
	return false
}

func (x *Detection) GetTripling() bool {
	if x != nil && x.Tripling != nil {
		return *x.Tripling
	}
	return false
}

func (x *Detection) GetMergedBbox() []float32 {
	if x != nil {
		return x.MergedBbox
	}
	return nil
}

func (x *Detection) GetTriplingMergedBbox() []float32 {
	if x != nil {
		return x.TriplingMergedBbox
	}
	return nil
}

func (x *Detection) GetIsIntrusion() bool {
	if x != nil && x.IsIntrusion != nil {
		return *x.IsIntrusion
	}
	return false
}

func (x *Detection) GetPlate() string {
	if x != nil && x.Plate != nil {
		return *x.Plate
	}
	return ""
}

func (x *Detection) GetPlateBbox() []float32 {
	if x != nil {
		return x.PlateBbox
	}
	return nil
}

func (x *Detection) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *Detection) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *Detection) GetIsLoitering() bool {
	if x != nil && x.IsLoitering != nil {
		return *x.IsLoitering
	}
	return false
}

func (x *Detection) GetTimeInRegion() float32 {
	if x != nil && x.TimeInRegion != nil {
		return *x.TimeInRegion
	}
	return 0
}

func (x *Detection) GetVesselType() string {
	if x != nil && x.VesselType != nil {
		return *x.VesselType
	}
	return ""
}

func (x *Detection) GetRecognitionId() string {
	if x != nil && x.RecognitionId != nil {
		return *x.RecognitionId
	}
	return ""
}

func (x *Detection) GetRecognitionScore() float32 {
	if x != nil && x.RecognitionScore != nil {
		return *x.RecognitionScore
	}
	return 0
}

func (x *Detection) GetRedlightViolation() bool {
	if x != nil && x.RedlightViolation != nil {
		return *x.RedlightViolation
	}
	return false
}

func (x *Detection) GetSpeedKmph() float32 {
	if x != nil && x.SpeedKmph != nil {
		return *x.SpeedKmph
	}
	return 0
}

func (x *Detection) GetWrongLane() bool {
	if x != nil && x.WrongLane != nil {
		return *x.WrongLane
	}
	return false
}

type CrowdInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rectangle     []float32              `protobuf:"fixed32,1,rep,packed,name=rectangle,proto3" json:"rectangle,omitempty"` // [x1, y1, x2, y2]
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AlertLevel    string                 `protobuf:"bytes,3,opt,name=alert_level,json=alertLevel,proto3" json:"alert_level,omitempty"` // "low", "medium", "high"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrowdInfo) Reset() {
	*x = CrowdInfo{}
	mi := &file_proto_detection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrowdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrowdInfo) ProtoMessage() {}

func (x *CrowdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrowdInfo.ProtoReflect.Descriptor instead.
func (*CrowdInfo) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{12}
}

func (x *CrowdInfo) GetRectangle() []float32 {
	if x != nil {
		return x.Rectangle
	}
	return nil
}

func (x *CrowdInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CrowdInfo) GetAlertLevel() string {
	if x != nil {
		return x.AlertLevel
	}
	return ""
}

type CrowdDetectionResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Crowds           []*CrowdInfo           `protobuf:"bytes,1,rep,name=crowds,proto3" json:"crowds,omitempty"`
	TotalCrowdPeople int32                  `protobuf:"varint,2,opt,name=total_crowd_people,json=totalCrowdPeople,proto3" json:"total_crowd_people,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CrowdDetectionResult) Reset() {
	*x = CrowdDetectionResult{}
	mi := &file_proto_detection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrowdDetectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrowdDetectionResult) ProtoMessage() {}

func (x *CrowdDetectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrowdDetectionResult.ProtoReflect.Descriptor instead.
func (*CrowdDetectionResult) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{13}
}

func (x *CrowdDetectionResult) GetCrowds() []*CrowdInfo {
	if x != nil {
		return x.Crowds
	}
	return nil
}

func (x *CrowdDetectionResult) GetTotalCrowdPeople() int32 {
	if x != nil {
		return x.TotalCrowdPeople
	}
	return 0
}

type VehicleCrowdInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rectangle     []float32              `protobuf:"fixed32,1,rep,packed,name=rectangle,proto3" json:"rectangle,omitempty"` // [x1, y1, x2, y2]
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AlertLevel    string                 `protobuf:"bytes,3,opt,name=alert_level,json=alertLevel,proto3" json:"alert_level,omitempty"` // "low", "medium", "high"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleCrowdInfo) Reset() {
	*x = VehicleCrowdInfo{}
	mi := &file_proto_detection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleCrowdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleCrowdInfo) ProtoMessage() {}

func (x *VehicleCrowdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleCrowdInfo.ProtoReflect.Descriptor instead.
func (*VehicleCrowdInfo) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{14}
}

func (x *VehicleCrowdInfo) GetRectangle() []float32 {
	if x != nil {
		return x.Rectangle
	}
	return nil
}

func (x *VehicleCrowdInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *VehicleCrowdInfo) GetAlertLevel() string {
	if x != nil {
		return x.AlertLevel
	}
	return ""
}

type VehicleCrowdDetectionResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Crowds             []*VehicleCrowdInfo    `protobuf:"bytes,1,rep,name=crowds,proto3" json:"crowds,omitempty"`
	TotalCrowdVehicles int32                  `protobuf:"varint,2,opt,name=total_crowd_vehicles,json=totalCrowdVehicles,proto3" json:"total_crowd_vehicles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VehicleCrowdDetectionResult) Reset() {
	*x = VehicleCrowdDetectionResult{}
	mi := &file_proto_detection_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleCrowdDetectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleCrowdDetectionResult) ProtoMessage() {}

func (x *VehicleCrowdDetectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleCrowdDetectionResult.ProtoReflect.Descriptor instead.
func (*VehicleCrowdDetectionResult) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{15}
}

func (x *VehicleCrowdDetectionResult) GetCrowds() []*VehicleCrowdInfo {
	if x != nil {
		return x.Crowds
	}
	return nil
}

func (x *VehicleCrowdDetectionResult) GetTotalCrowdVehicles() int32 {
	if x != nil {
		return x.TotalCrowdVehicles
	}
	return 0
}

// Solution result
type SolutionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PPE Alerts
	ViolationDetected *bool    `protobuf:"varint,1,opt,name=violation_detected,json=violationDetected,proto3,oneof" json:"violation_detected,omitempty"`
	LastViolationTime *float32 `protobuf:"fixed32,2,opt,name=last_violation_time,json=lastViolationTime,proto3,oneof" json:"last_violation_time,omitempty"`
	CurrentViolations []string `protobuf:"bytes,3,rep,name=current_violations,json=currentViolations,proto3" json:"current_violations,omitempty"`
	// People Counter
	InRegionTracks []int32 `protobuf:"varint,4,rep,packed,name=in_region_tracks,json=inRegionTracks,proto3" json:"in_region_tracks,omitempty"`
	CurrentCount   *int32  `protobuf:"varint,5,opt,name=current_count,json=currentCount,proto3,oneof" json:"current_count,omitempty"`
	OutRegionCount *int32  `protobuf:"varint,16,opt,name=out_region_count,json=outRegionCount,proto3,oneof" json:"out_region_count,omitempty"`
	TotalCount     *int32  `protobuf:"varint,6,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
	MaxCount       *int32  `protobuf:"varint,7,opt,name=max_count,json=maxCount,proto3,oneof" json:"max_count,omitempty"`
	// Vehicle Counter
	VehicleInRegionTracks []int32 `protobuf:"varint,19,rep,packed,name=vehicle_in_region_tracks,json=vehicleInRegionTracks,proto3" json:"vehicle_in_region_tracks,omitempty"`
	VehicleCurrentCount   *int32  `protobuf:"varint,20,opt,name=vehicle_current_count,json=vehicleCurrentCount,proto3,oneof" json:"vehicle_current_count,omitempty"`
	VehicleOutRegionCount *int32  `protobuf:"varint,21,opt,name=vehicle_out_region_count,json=vehicleOutRegionCount,proto3,oneof" json:"vehicle_out_region_count,omitempty"`
	VehicleTotalCount     *int32  `protobuf:"varint,22,opt,name=vehicle_total_count,json=vehicleTotalCount,proto3,oneof" json:"vehicle_total_count,omitempty"`
	VehicleMaxCount       *int32  `protobuf:"varint,23,opt,name=vehicle_max_count,json=vehicleMaxCount,proto3,oneof" json:"vehicle_max_count,omitempty"`
	// Intrusion Detection
	IntrusionDetected *bool    `protobuf:"varint,8,opt,name=intrusion_detected,json=intrusionDetected,proto3,oneof" json:"intrusion_detected,omitempty"`
	LastIntrusionTime *float32 `protobuf:"fixed32,9,opt,name=last_intrusion_time,json=lastIntrusionTime,proto3,oneof" json:"last_intrusion_time,omitempty"`
	IntruderTracks    []int32  `protobuf:"varint,10,rep,packed,name=intruder_tracks,json=intruderTracks,proto3" json:"intruder_tracks,omitempty"`
	// Cloth Color Detection
	ClothingColors []*ColorResult `protobuf:"bytes,12,rep,name=clothing_colors,json=clothingColors,proto3" json:"clothing_colors,omitempty"`
	// Crowd Detection (for people)
	CrowdDetection *CrowdDetectionResult `protobuf:"bytes,13,opt,name=crowd_detection,json=crowdDetection,proto3,oneof" json:"crowd_detection,omitempty"`
	// Vehicle Crowd Detection
	VehicleCrowdDetection *VehicleCrowdDetectionResult `protobuf:"bytes,18,opt,name=vehicle_crowd_detection,json=vehicleCrowdDetection,proto3,oneof" json:"vehicle_crowd_detection,omitempty"`
	// Loitering Detection
	LoiteringDetected *bool `protobuf:"varint,15,opt,name=loitering_detected,json=loiteringDetected,proto3,oneof" json:"loitering_detected,omitempty"`
	// Status string for solutions
	Status        *string `protobuf:"bytes,17,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolutionResult) Reset() {
	*x = SolutionResult{}
	mi := &file_proto_detection_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolutionResult) ProtoMessage() {}

func (x *SolutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolutionResult.ProtoReflect.Descriptor instead.
func (*SolutionResult) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{16}
}

func (x *SolutionResult) GetViolationDetected() bool {
	if x != nil && x.ViolationDetected != nil {
		return *x.ViolationDetected
	}
	return false
}

func (x *SolutionResult) GetLastViolationTime() float32 {
	if x != nil && x.LastViolationTime != nil {
		return *x.LastViolationTime
	}
	return 0
}

func (x *SolutionResult) GetCurrentViolations() []string {
	if x != nil {
		return x.CurrentViolations
	}
	return nil
}

func (x *SolutionResult) GetInRegionTracks() []int32 {
	if x != nil {
		return x.InRegionTracks
	}
	return nil
}

func (x *SolutionResult) GetCurrentCount() int32 {
	if x != nil && x.CurrentCount != nil {
		return *x.CurrentCount
	}
	return 0
}

func (x *SolutionResult) GetOutRegionCount() int32 {
	if x != nil && x.OutRegionCount != nil {
		return *x.OutRegionCount
	}
	return 0
}

func (x *SolutionResult) GetTotalCount() int32 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

func (x *SolutionResult) GetMaxCount() int32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	return 0
}

func (x *SolutionResult) GetVehicleInRegionTracks() []int32 {
	if x != nil {
		return x.VehicleInRegionTracks
	}
	return nil
}

func (x *SolutionResult) GetVehicleCurrentCount() int32 {
	if x != nil && x.VehicleCurrentCount != nil {
		return *x.VehicleCurrentCount
	}
	return 0
}

func (x *SolutionResult) GetVehicleOutRegionCount() int32 {
	if x != nil && x.VehicleOutRegionCount != nil {
		return *x.VehicleOutRegionCount
	}
	return 0
}

func (x *SolutionResult) GetVehicleTotalCount() int32 {
	if x != nil && x.VehicleTotalCount != nil {
		return *x.VehicleTotalCount
	}
	return 0
}

func (x *SolutionResult) GetVehicleMaxCount() int32 {
	if x != nil && x.VehicleMaxCount != nil {
		return *x.VehicleMaxCount
	}
	return 0
}

func (x *SolutionResult) GetIntrusionDetected() bool {
	if x != nil && x.IntrusionDetected != nil {
		return *x.IntrusionDetected
	}
	return false
}

func (x *SolutionResult) GetLastIntrusionTime() float32 {
	if x != nil && x.LastIntrusionTime != nil {
		return *x.LastIntrusionTime
	}
	return 0
}

func (x *SolutionResult) GetIntruderTracks() []int32 {
	if x != nil {
		return x.IntruderTracks
	}
	return nil
}

func (x *SolutionResult) GetClothingColors() []*ColorResult {
	if x != nil {
		return x.ClothingColors
	}
	return nil
}

func (x *SolutionResult) GetCrowdDetection() *CrowdDetectionResult {
	if x != nil {
		return x.CrowdDetection
	}
	return nil
}

func (x *SolutionResult) GetVehicleCrowdDetection() *VehicleCrowdDetectionResult {
	if x != nil {
		return x.VehicleCrowdDetection
	}
	return nil
}

func (x *SolutionResult) GetLoiteringDetected() bool {
	if x != nil && x.LoiteringDetected != nil {
		return *x.LoiteringDetected
	}
	return false
}

func (x *SolutionResult) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ColorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         string                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	TrackId       int32                  `protobuf:"varint,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorResult) Reset() {
	*x = ColorResult{}
	mi := &file_proto_detection_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorResult) ProtoMessage() {}

func (x *ColorResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorResult.ProtoReflect.Descriptor instead.
func (*ColorResult) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{17}
}

func (x *ColorResult) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ColorResult) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

// Response message for status endpoints
type StatusResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Optional fields
	CameraId           string `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	PipelinesRemoved   int32  `protobuf:"varint,4,opt,name=pipelines_removed,json=pipelinesRemoved,proto3" json:"pipelines_removed,omitempty"`
	RemainingPipelines int32  `protobuf:"varint,5,opt,name=remaining_pipelines,json=remainingPipelines,proto3" json:"remaining_pipelines,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_detection_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{18}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *StatusResponse) GetPipelinesRemoved() int32 {
	if x != nil {
		return x.PipelinesRemoved
	}
	return 0
}

func (x *StatusResponse) GetRemainingPipelines() int32 {
	if x != nil {
		return x.RemainingPipelines
	}
	return 0
}

// Response message for health check
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_detection_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{19}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Response message for active pipelines
type PipelinesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActivePipelines []string               `protobuf:"bytes,1,rep,name=active_pipelines,json=activePipelines,proto3" json:"active_pipelines,omitempty"`
	Count           int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PipelinesResponse) Reset() {
	*x = PipelinesResponse{}
	mi := &file_proto_detection_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelinesResponse) ProtoMessage() {}

func (x *PipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelinesResponse.ProtoReflect.Descriptor instead.
func (*PipelinesResponse) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{20}
}

func (x *PipelinesResponse) GetActivePipelines() []string {
	if x != nil {
		return x.ActivePipelines
	}
	return nil
}

func (x *PipelinesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Request message for adding a face to the database
type AddFaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"` // Unique ID for the image/face
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`                    // Base64 encoded image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFaceRequest) Reset() {
	*x = AddFaceRequest{}
	mi := &file_proto_detection_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFaceRequest) ProtoMessage() {}

func (x *AddFaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFaceRequest.ProtoReflect.Descriptor instead.
func (*AddFaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{21}
}

func (x *AddFaceRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *AddFaceRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *AddFaceRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// Request message for toggling outlier detection
type ToggleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // true to enable, false to disable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleRequest) Reset() {
	*x = ToggleRequest{}
	mi := &file_proto_detection_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleRequest) ProtoMessage() {}

func (x *ToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleRequest.ProtoReflect.Descriptor instead.
func (*ToggleRequest) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{22}
}

func (x *ToggleRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *ToggleRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// Response message for toggle operations
type ToggleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleResponse) Reset() {
	*x = ToggleResponse{}
	mi := &file_proto_detection_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleResponse) ProtoMessage() {}

func (x *ToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_detection_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleResponse.ProtoReflect.Descriptor instead.
func (*ToggleResponse) Descriptor() ([]byte, []int) {
	return file_proto_detection_proto_rawDescGZIP(), []int{23}
}

func (x *ToggleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToggleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_detection_proto protoreflect.FileDescriptor

const file_proto_detection_proto_rawDesc = "" +
	"\n" +
	"\x15proto/detection.proto\x12\tdetection\"\a\n" +
	"\x05Empty\".\n" +
	"\x0fCameraIdRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"f\n" +
	"\fFrameRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\tR\bcameraId\x12#\n" +
	"\rproject_names\x18\x03 \x03(\tR\fprojectNames\"\x98\x01\n" +
	"\n" +
	"ROIRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\tR\bcameraId\x12\x15\n" +
	"\x06roi_id\x18\x03 \x01(\tR\x05roiId\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\"\x88\x01\n" +
	"\x10RemoveROIRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x15\n" +
	"\x06roi_id\x18\x02 \x01(\tR\x05roiId\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\"\x8d\x01\n" +
	"\x14TrueDetectionRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12\x1f\n" +
	"\vobject_type\x18\x04 \x01(\tR\n" +
	"objectType\"\xb6\x01\n" +
	"\x1aRemoveTrueDetectionRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12\x1f\n" +
	"\vobject_type\x18\x03 \x01(\tR\n" +
	"objectType\x12&\n" +
	"\fdetection_id\x18\x04 \x01(\tH\x00R\vdetectionId\x88\x01\x01B\x0f\n" +
	"\r_detection_id\"\x1f\n" +
	"\x05point\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xa4\x01\n" +
	"\x12SolutionROIRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12#\n" +
	"\rsolution_name\x18\x03 \x01(\tR\fsolutionName\x12)\n" +
	"\aroi_pts\x18\x04 \x03(\v2\x10.detection.pointR\x06roiPts\"\xb2\x01\n" +
	"\x11DetectionResponse\x12C\n" +
	"\aresults\x18\x01 \x03(\v2).detection.DetectionResponse.ResultsEntryR\aresults\x1aX\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.detection.ProjectDetectionsR\x05value:\x028\x01\"\x8c\x03\n" +
	"\x11ProjectDetections\x12C\n" +
	"\x12primary_detections\x18\x01 \x03(\v2\x14.detection.DetectionR\x11primaryDetections\x12G\n" +
	"\x14secondary_detections\x18\x02 \x03(\v2\x14.detection.DetectionR\x13secondaryDetections\x12E\n" +
	"\x13tertiary_detections\x18\x03 \x03(\v2\x14.detection.DetectionR\x12tertiaryDetections\x12I\n" +
	"\tsolutions\x18\x04 \x03(\v2+.detection.ProjectDetections.SolutionsEntryR\tsolutions\x1aW\n" +
	"\x0eSolutionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.detection.SolutionResultR\x05value:\x028\x01\"\xbd\f\n" +
	"\tDetection\x12\x12\n" +
	"\x04bbox\x18\x01 \x03(\x02R\x04bbox\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\x05R\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\x12\x19\n" +
	"\btrack_id\x18\x05 \x01(\x05R\atrackId\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x05R\bparentId\x12$\n" +
	"\x0efalse_match_id\x18\a \x01(\tR\ffalseMatchId\x12\x1d\n" +
	"\n" +
	"send_alert\x18\b \x01(\bR\tsendAlert\x12\x1b\n" +
	"\tframe_num\x18\t \x01(\x05R\bframeNum\x12\x15\n" +
	"\x06is_rpn\x18\x1b \x01(\bR\x05isRpn\x12'\n" +
	"\rtrue_match_id\x18\x1c \x01(\tH\x00R\vtrueMatchId\x88\x01\x01\x12\x1e\n" +
	"\bhas_vest\x18\n" +
	" \x01(\bH\x01R\ahasVest\x88\x01\x01\x12\"\n" +
	"\n" +
	"has_helmet\x18\v \x01(\bH\x02R\thasHelmet\x88\x01\x01\x12\x1e\n" +
	"\bhas_head\x18\x1a \x01(\bH\x03R\ahasHead\x88\x01\x01\x12#\n" +
	"\n" +
	"compliance\x18\f \x01(\tH\x04R\n" +
	"compliance\x88\x01\x01\x12\"\n" +
	"\n" +
	"has_gloves\x18\r \x01(\bH\x05R\thasGloves\x88\x01\x01\x12$\n" +
	"\vhas_glasses\x18\x0e \x01(\bH\x06R\n" +
	"hasGlasses\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"violations\x18\x0f \x03(\tR\n" +
	"violations\x12\x1b\n" +
	"\tppe_items\x18\x10 \x03(\tR\bppeItems\x12+\n" +
	"\x0fhas_bike_helmet\x18\x1d \x01(\bH\aR\rhasBikeHelmet\x88\x01\x01\x12\x1f\n" +
	"\btripling\x18\x1e \x01(\bH\bR\btripling\x88\x01\x01\x12\x1f\n" +
	"\vmerged_bbox\x18\x1f \x03(\x02R\n" +
	"mergedBbox\x120\n" +
	"\x14tripling_merged_bbox\x18  \x03(\x02R\x12triplingMergedBbox\x12&\n" +
	"\fis_intrusion\x18\x11 \x01(\bH\tR\visIntrusion\x88\x01\x01\x12\x19\n" +
	"\x05plate\x18\x12 \x01(\tH\n" +
	"R\x05plate\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"plate_bbox\x18$ \x03(\x02R\tplateBbox\x12\x19\n" +
	"\x05color\x18\x13 \x01(\tH\vR\x05color\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x14 \x01(\tH\fR\x06gender\x88\x01\x01\x12&\n" +
	"\fis_loitering\x18\x15 \x01(\bH\rR\visLoitering\x88\x01\x01\x12)\n" +
	"\x0etime_in_region\x18\x16 \x01(\x02H\x0eR\ftimeInRegion\x88\x01\x01\x12$\n" +
	"\vvessel_type\x18\x17 \x01(\tH\x0fR\n" +
	"vesselType\x88\x01\x01\x12*\n" +
	"\x0erecognition_id\x18\x18 \x01(\tH\x10R\rrecognitionId\x88\x01\x01\x120\n" +
	"\x11recognition_score\x18\x19 \x01(\x02H\x11R\x10recognitionScore\x88\x01\x01\x122\n" +
	"\x12redlight_violation\x18! \x01(\bH\x12R\x11redlightViolation\x88\x01\x01\x12\"\n" +
	"\n" +
	"speed_kmph\x18\" \x01(\x02H\x13R\tspeedKmph\x88\x01\x01\x12\"\n" +
	"\n" +
	"wrong_lane\x18# \x01(\bH\x14R\twrongLane\x88\x01\x01B\x10\n" +
	"\x0e_true_match_idB\v\n" +
	"\t_has_vestB\r\n" +
	"\v_has_helmetB\v\n" +
	"\t_has_headB\r\n" +
	"\v_complianceB\r\n" +
	"\v_has_glovesB\x0e\n" +
	"\f_has_glassesB\x12\n" +
	"\x10_has_bike_helmetB\v\n" +
	"\t_triplingB\x0f\n" +
	"\r_is_intrusionB\b\n" +
	"\x06_plateB\b\n" +
	"\x06_colorB\t\n" +
	"\a_genderB\x0f\n" +
	"\r_is_loiteringB\x11\n" +
	"\x0f_time_in_regionB\x0e\n" +
	"\f_vessel_typeB\x11\n" +
	"\x0f_recognition_idB\x14\n" +
	"\x12_recognition_scoreB\x15\n" +
	"\x13_redlight_violationB\r\n" +
	"\v_speed_kmphB\r\n" +
	"\v_wrong_lane\"`\n" +
	"\tCrowdInfo\x12\x1c\n" +
	"\trectangle\x18\x01 \x03(\x02R\trectangle\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1f\n" +
	"\valert_level\x18\x03 \x01(\tR\n" +
	"alertLevel\"r\n" +
	"\x14CrowdDetectionResult\x12,\n" +
	"\x06crowds\x18\x01 \x03(\v2\x14.detection.CrowdInfoR\x06crowds\x12,\n" +
	"\x12total_crowd_people\x18\x02 \x01(\x05R\x10totalCrowdPeople\"g\n" +
	"\x10VehicleCrowdInfo\x12\x1c\n" +
	"\trectangle\x18\x01 \x03(\x02R\trectangle\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1f\n" +
	"\valert_level\x18\x03 \x01(\tR\n" +
	"alertLevel\"\x84\x01\n" +
	"\x1bVehicleCrowdDetectionResult\x123\n" +
	"\x06crowds\x18\x01 \x03(\v2\x1b.detection.VehicleCrowdInfoR\x06crowds\x120\n" +
	"\x14total_crowd_vehicles\x18\x02 \x01(\x05R\x12totalCrowdVehicles\"\xbb\v\n" +
	"\x0eSolutionResult\x122\n" +
	"\x12violation_detected\x18\x01 \x01(\bH\x00R\x11violationDetected\x88\x01\x01\x123\n" +
	"\x13last_violation_time\x18\x02 \x01(\x02H\x01R\x11lastViolationTime\x88\x01\x01\x12-\n" +
	"\x12current_violations\x18\x03 \x03(\tR\x11currentViolations\x12(\n" +
	"\x10in_region_tracks\x18\x04 \x03(\x05R\x0einRegionTracks\x12(\n" +
	"\rcurrent_count\x18\x05 \x01(\x05H\x02R\fcurrentCount\x88\x01\x01\x12-\n" +
	"\x10out_region_count\x18\x10 \x01(\x05H\x03R\x0eoutRegionCount\x88\x01\x01\x12$\n" +
	"\vtotal_count\x18\x06 \x01(\x05H\x04R\n" +
	"totalCount\x88\x01\x01\x12 \n" +
	"\tmax_count\x18\a \x01(\x05H\x05R\bmaxCount\x88\x01\x01\x127\n" +
	"\x18vehicle_in_region_tracks\x18\x13 \x03(\x05R\x15vehicleInRegionTracks\x127\n" +
	"\x15vehicle_current_count\x18\x14 \x01(\x05H\x06R\x13vehicleCurrentCount\x88\x01\x01\x12<\n" +
	"\x18vehicle_out_region_count\x18\x15 \x01(\x05H\aR\x15vehicleOutRegionCount\x88\x01\x01\x123\n" +
	"\x13vehicle_total_count\x18\x16 \x01(\x05H\bR\x11vehicleTotalCount\x88\x01\x01\x12/\n" +
	"\x11vehicle_max_count\x18\x17 \x01(\x05H\tR\x0fvehicleMaxCount\x88\x01\x01\x122\n" +
	"\x12intrusion_detected\x18\b \x01(\bH\n" +
	"R\x11intrusionDetected\x88\x01\x01\x123\n" +
	"\x13last_intrusion_time\x18\t \x01(\x02H\vR\x11lastIntrusionTime\x88\x01\x01\x12'\n" +
	"\x0fintruder_tracks\x18\n" +
	" \x03(\x05R\x0eintruderTracks\x12?\n" +
	"\x0fclothing_colors\x18\f \x03(\v2\x16.detection.ColorResultR\x0eclothingColors\x12M\n" +
	"\x0fcrowd_detection\x18\r \x01(\v2\x1f.detection.CrowdDetectionResultH\fR\x0ecrowdDetection\x88\x01\x01\x12c\n" +
	"\x17vehicle_crowd_detection\x18\x12 \x01(\v2&.detection.VehicleCrowdDetectionResultH\rR\x15vehicleCrowdDetection\x88\x01\x01\x122\n" +
	"\x12loitering_detected\x18\x0f \x01(\bH\x0eR\x11loiteringDetected\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x11 \x01(\tH\x0fR\x06status\x88\x01\x01B\x15\n" +
	"\x13_violation_detectedB\x16\n" +
	"\x14_last_violation_timeB\x10\n" +
	"\x0e_current_countB\x13\n" +
	"\x11_out_region_countB\x0e\n" +
	"\f_total_countB\f\n" +
	"\n" +
	"_max_countB\x18\n" +
	"\x16_vehicle_current_countB\x1b\n" +
	"\x19_vehicle_out_region_countB\x16\n" +
	"\x14_vehicle_total_countB\x14\n" +
	"\x12_vehicle_max_countB\x15\n" +
	"\x13_intrusion_detectedB\x16\n" +
	"\x14_last_intrusion_timeB\x12\n" +
	"\x10_crowd_detectionB\x1a\n" +
	"\x18_vehicle_crowd_detectionB\x15\n" +
	"\x13_loitering_detectedB\t\n" +
	"\a_status\">\n" +
	"\vColorResult\x12\x14\n" +
	"\x05color\x18\x01 \x01(\tR\x05color\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\x05R\atrackId\"\xbd\x01\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tcamera_id\x18\x03 \x01(\tR\bcameraId\x12+\n" +
	"\x11pipelines_removed\x18\x04 \x01(\x05R\x10pipelinesRemoved\x12/\n" +
	"\x13remaining_pipelines\x18\x05 \x01(\x05R\x12remainingPipelines\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"T\n" +
	"\x11PipelinesResponse\x12)\n" +
	"\x10active_pipelines\x18\x01 \x03(\tR\x0factivePipelines\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"^\n" +
	"\x0eAddFaceRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\"@\n" +
	"\rToggleRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"B\n" +
	"\x0eToggleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc7\x06\n" +
	"\x10DetectionService\x12I\n" +
	"\x0eInferDetection\x12\x17.detection.FrameRequest\x1a\x1c.detection.DetectionResponse\"\x00\x12H\n" +
	"\x12SaveFalseDetection\x12\x15.detection.ROIRequest\x1a\x19.detection.StatusResponse\"\x00\x12P\n" +
	"\x14RemoveFalseDetection\x12\x1b.detection.RemoveROIRequest\x1a\x19.detection.StatusResponse\"\x00\x12Q\n" +
	"\x11SaveTrueDetection\x12\x1f.detection.TrueDetectionRequest\x1a\x19.detection.StatusResponse\"\x00\x12Y\n" +
	"\x13RemoveTrueDetection\x12%.detection.RemoveTrueDetectionRequest\x1a\x19.detection.StatusResponse\"\x00\x12C\n" +
	"\n" +
	"ToggleMode\x12\x18.detection.ToggleRequest\x1a\x19.detection.ToggleResponse\"\x00\x12<\n" +
	"\vHealthCheck\x12\x10.detection.Empty\x1a\x19.detection.HealthResponse\"\x00\x12F\n" +
	"\x12GetActivePipelines\x12\x10.detection.Empty\x1a\x1c.detection.PipelinesResponse\"\x00\x12J\n" +
	"\x0fRemovePipelines\x12\x1a.detection.CameraIdRequest\x1a\x19.detection.StatusResponse\"\x00\x12D\n" +
	"\x06SetROI\x12\x1d.detection.SolutionROIRequest\x1a\x19.detection.StatusResponse\"\x00\x12A\n" +
	"\aAddFace\x12\x19.detection.AddFaceRequest\x1a\x19.detection.StatusResponse\"\x00B\x18Z\x16kepler-worker-go/protob\x06proto3"

var (
	file_proto_detection_proto_rawDescOnce sync.Once
	file_proto_detection_proto_rawDescData []byte
)

func file_proto_detection_proto_rawDescGZIP() []byte {
	file_proto_detection_proto_rawDescOnce.Do(func() {
		file_proto_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_detection_proto_rawDesc), len(file_proto_detection_proto_rawDesc)))
	})
	return file_proto_detection_proto_rawDescData
}

var file_proto_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_detection_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: detection.Empty
	(*CameraIdRequest)(nil),             // 1: detection.CameraIdRequest
	(*FrameRequest)(nil),                // 2: detection.FrameRequest
	(*ROIRequest)(nil),                  // 3: detection.ROIRequest
	(*RemoveROIRequest)(nil),            // 4: detection.RemoveROIRequest
	(*TrueDetectionRequest)(nil),        // 5: detection.TrueDetectionRequest
	(*RemoveTrueDetectionRequest)(nil),  // 6: detection.RemoveTrueDetectionRequest
	(*Point)(nil),                       // 7: detection.point
	(*SolutionROIRequest)(nil),          // 8: detection.SolutionROIRequest
	(*DetectionResponse)(nil),           // 9: detection.DetectionResponse
	(*ProjectDetections)(nil),           // 10: detection.ProjectDetections
	(*Detection)(nil),                   // 11: detection.Detection
	(*CrowdInfo)(nil),                   // 12: detection.CrowdInfo
	(*CrowdDetectionResult)(nil),        // 13: detection.CrowdDetectionResult
	(*VehicleCrowdInfo)(nil),            // 14: detection.VehicleCrowdInfo
	(*VehicleCrowdDetectionResult)(nil), // 15: detection.VehicleCrowdDetectionResult
	(*SolutionResult)(nil),              // 16: detection.SolutionResult
	(*ColorResult)(nil),                 // 17: detection.ColorResult
	(*StatusResponse)(nil),              // 18: detection.StatusResponse
	(*HealthResponse)(nil),              // 19: detection.HealthResponse
	(*PipelinesResponse)(nil),           // 20: detection.PipelinesResponse
	(*AddFaceRequest)(nil),              // 21: detection.AddFaceRequest
	(*ToggleRequest)(nil),               // 22: detection.ToggleRequest
	(*ToggleResponse)(nil),              // 23: detection.ToggleResponse
	nil,                                 // 24: detection.DetectionResponse.ResultsEntry
	nil,                                 // 25: detection.ProjectDetections.SolutionsEntry
}
var file_proto_detection_proto_depIdxs = []int32{
	7,  // 0: detection.SolutionROIRequest.roi_pts:type_name -> detection.point
	24, // 1: detection.DetectionResponse.results:type_name -> detection.DetectionResponse.ResultsEntry
	11, // 2: detection.ProjectDetections.primary_detections:type_name -> detection.Detection
	11, // 3: detection.ProjectDetections.secondary_detections:type_name -> detection.Detection
	11, // 4: detection.ProjectDetections.tertiary_detections:type_name -> detection.Detection
	25, // 5: detection.ProjectDetections.solutions:type_name -> detection.ProjectDetections.SolutionsEntry
	12, // 6: detection.CrowdDetectionResult.crowds:type_name -> detection.CrowdInfo
	14, // 7: detection.VehicleCrowdDetectionResult.crowds:type_name -> detection.VehicleCrowdInfo
	17, // 8: detection.SolutionResult.clothing_colors:type_name -> detection.ColorResult
	13, // 9: detection.SolutionResult.crowd_detection:type_name -> detection.CrowdDetectionResult
	15, // 10: detection.SolutionResult.vehicle_crowd_detection:type_name -> detection.VehicleCrowdDetectionResult
	10, // 11: detection.DetectionResponse.ResultsEntry.value:type_name -> detection.ProjectDetections
	16, // 12: detection.ProjectDetections.SolutionsEntry.value:type_name -> detection.SolutionResult
	2,  // 13: detection.DetectionService.InferDetection:input_type -> detection.FrameRequest
	3,  // 14: detection.DetectionService.SaveFalseDetection:input_type -> detection.ROIRequest
	4,  // 15: detection.DetectionService.RemoveFalseDetection:input_type -> detection.RemoveROIRequest
	5,  // 16: detection.DetectionService.SaveTrueDetection:input_type -> detection.TrueDetectionRequest
	6,  // 17: detection.DetectionService.RemoveTrueDetection:input_type -> detection.RemoveTrueDetectionRequest
	22, // 18: detection.DetectionService.ToggleMode:input_type -> detection.ToggleRequest
	0,  // 19: detection.DetectionService.HealthCheck:input_type -> detection.Empty
	0,  // 20: detection.DetectionService.GetActivePipelines:input_type -> detection.Empty
	1,  // 21: detection.DetectionService.RemovePipelines:input_type -> detection.CameraIdRequest
	8,  // 22: detection.DetectionService.SetROI:input_type -> detection.SolutionROIRequest
	21, // 23: detection.DetectionService.AddFace:input_type -> detection.AddFaceRequest
	9,  // 24: detection.DetectionService.InferDetection:output_type -> detection.DetectionResponse
	18, // 25: detection.DetectionService.SaveFalseDetection:output_type -> detection.StatusResponse
	18, // 26: detection.DetectionService.RemoveFalseDetection:output_type -> detection.StatusResponse
	18, // 27: detection.DetectionService.SaveTrueDetection:output_type -> detection.StatusResponse
	18, // 28: detection.DetectionService.RemoveTrueDetection:output_type -> detection.StatusResponse
	23, // 29: detection.DetectionService.ToggleMode:output_type -> detection.ToggleResponse
	19, // 30: detection.DetectionService.HealthCheck:output_type -> detection.HealthResponse
	20, // 31: detection.DetectionService.GetActivePipelines:output_type -> detection.PipelinesResponse
	18, // 32: detection.DetectionService.RemovePipelines:output_type -> detection.StatusResponse
	18, // 33: detection.DetectionService.SetROI:output_type -> detection.StatusResponse
	18, // 34: detection.DetectionService.AddFace:output_type -> detection.StatusResponse
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_detection_proto_init() }
func file_proto_detection_proto_init() {
	if File_proto_detection_proto != nil {
		return
	}
	file_proto_detection_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_detection_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_detection_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_detection_proto_rawDesc), len(file_proto_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_detection_proto_goTypes,
		DependencyIndexes: file_proto_detection_proto_depIdxs,
		MessageInfos:      file_proto_detection_proto_msgTypes,
	}.Build()
	File_proto_detection_proto = out.File
	file_proto_detection_proto_goTypes = nil
	file_proto_detection_proto_depIdxs = nil
}
