// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cameras": {
            "get": {
                "description": "Get list of all cameras and their status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cameras"
                ],
                "summary": "List all cameras",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CameraListResponse"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/start": {
            "post": {
                "description": "Start processing for a camera with RTSP stream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cameras"
                ],
                "summary": "Start camera processing",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Camera configuration",
                        "name": "camera",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.StartCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CameraResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cameras/{id}/status": {
            "get": {
                "description": "Get detailed status of a specific camera",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cameras"
                ],
                "summary": "Get camera status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CameraStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cameras/{id}/stop": {
            "post": {
                "description": "Stop processing for a camera",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cameras"
                ],
                "summary": "Stop camera processing",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CameraResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the worker is healthy and responsive",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/webrtc/stats": {
            "get": {
                "description": "Get WebRTC publishing statistics for a camera or all cameras",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webrtc"
                ],
                "summary": "Get WebRTC statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID (optional, returns all if not specified)",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/webrtc/{id}/urls": {
            "get": {
                "description": "Get streaming URLs for all formats (HLS, WebRTC, RTSP) for a camera",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webrtc"
                ],
                "summary": "Get stream URLs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.StreamURLsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CameraListResponse": {
            "type": "object",
            "properties": {
                "cameras": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.CameraResponse"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handlers.CameraResponse": {
            "type": "object",
            "properties": {
                "camera_id": {
                    "type": "string",
                    "example": "test-camera"
                },
                "message": {
                    "type": "string",
                    "example": "Camera started successfully"
                },
                "status": {
                    "type": "string",
                    "example": "started"
                },
                "stream_url": {
                    "type": "string",
                    "example": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-07-28T19:45:51Z"
                }
            }
        },
        "handlers.CameraStatusResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "camera_id": {
                    "type": "string",
                    "example": "test-camera"
                },
                "last_seen": {
                    "type": "string",
                    "example": "2025-07-28T19:45:51Z"
                },
                "processing_info": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "type": "string",
                    "example": "running"
                },
                "stream_info": {
                    "type": "object",
                    "additionalProperties": true
                },
                "uptime": {
                    "type": "string",
                    "example": "5m30s"
                },
                "webrtc_info": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "worker_id": {
                    "type": "string",
                    "example": "worker-1"
                }
            }
        },
        "handlers.StartCameraRequest": {
            "type": "object",
            "required": [
                "solutions",
                "stream_url"
            ],
            "properties": {
                "solutions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "person_detection",
                        "ppe_detection"
                    ]
                },
                "stream_url": {
                    "type": "string",
                    "example": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4"
                }
            }
        },
        "handlers.StreamURLsResponse": {
            "type": "object",
            "properties": {
                "camera_id": {
                    "type": "string",
                    "example": "test-camera"
                },
                "hls": {
                    "type": "string",
                    "example": "http://127.0.0.1:8888/camera_test-camera/index.m3u8"
                },
                "rtsp": {
                    "type": "string",
                    "example": "rtsp://127.0.0.1:8554/camera_test-camera"
                },
                "webrtc": {
                    "type": "string",
                    "example": "http://127.0.0.1:8889/camera_test-camera/whep"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
